{"uuid":"1fb6cafe-32a4-49f2-b781-feb2a6daa829","historyId":"a2ae4096228b428c7becd4c725fdaf58","fullName":"userAPI.enpoints.UserCRUD_operations.testUserApiChaining_Positive","labels":[{"name":"package","value":"userAPI.enpoints.UserCRUD_operations"},{"name":"testClass","value":"userAPI.enpoints.UserCRUD_operations"},{"name":"testMethod","value":"testUserApiChaining_Positive"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"userAPI.enpoints.UserCRUD_operations"},{"name":"host","value":"Archana"},{"name":"thread","value":"33996@Archana.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Positive Test: Create, Retrieve, and Delete User","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"com.poiji.exception.PoijiException: Problem occurred while reading data","trace":"java.lang.RuntimeException: com.poiji.exception.PoijiException: Problem occurred while reading data\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:809)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:734)\r\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)\r\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\nCaused by: com.poiji.exception.PoijiException: Problem occurred while reading data\r\n\tat com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:46)\r\n\tat com.poiji.bind.mapping.XSSFUnmarshallerFile.unmarshal(XSSFUnmarshallerFile.java:35)\r\n\tat com.poiji.bind.Poiji.fromExcel(Poiji.java:205)\r\n\tat com.poiji.bind.Poiji.fromExcel(Poiji.java:182)\r\n\tat userAPI.utilities.ExcelTestData.getUserTestData(ExcelTestData.java:24)\r\n\tat userAPI.enpoints.UserCRUD_operations.getUserData(UserCRUD_operations.java:18)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)\r\n\t... 25 more\r\nCaused by: org.apache.poi.openxml4j.exceptions.InvalidFormatException: Can't open the specified file input stream from file: '.src\\test\\resources\\Testdata\\POST_RESTAssured_testdata.xlsx'\r\n\tat org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:289)\r\n\tat com.poiji.bind.mapping.XSSFUnmarshallerFile.returnFromExcelFile(XSSFUnmarshallerFile.java:41)\r\n\t... 35 more\r\nCaused by: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file input stream from file: '.src\\test\\resources\\Testdata\\POST_RESTAssured_testdata.xlsx'\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:212)\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:199)\r\n\tat org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:287)\r\n\t... 36 more\r\nCaused by: java.nio.file.NoSuchFileException: .src\\test\\resources\\Testdata\\POST_RESTAssured_testdata.xlsx\r\n\tat java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)\r\n\tat java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)\r\n\tat java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)\r\n\tat java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)\r\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:379)\r\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:431)\r\n\tat java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)\r\n\tat java.base/java.nio.file.Files.newInputStream(Files.java:159)\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:209)\r\n\t... 38 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1739225137374,"stop":1739225137375}